import type { CareerNode } from "./types";

// Path to 100K seed: every capstone is a job you can actually be hired into
// with a certification / license / apprenticeship (never a college degree),
// AND that pays $100K on the job (base or realistic OT / shift-diff /
// commission at the role) within ~2 years of starting from zero. Where a role
// only realistically hits $100K in a specific metro or with relocation, that
// is called out in `hundredKPath`.
//
// Layout is a 1000x1000 canvas radiating out from (500, 500).

export const CAREERS: CareerNode[] = [
  // =========================================================================
  // SKILLED TRADES (upper left)
  // =========================================================================
  {
    id: "elevator-mechanic",
    name: "Elevator Mechanic",
    branch: "trades",
    tier: 3,
    medianSalary: 102000,
    hundredKPath:
      "IUEC (union) apprentices earn ~$50-70K starting; scale hits $100K+ at journeyman/mechanic (yr 3-4). Waiting lists — move for an open slot.",
    entryMonths: 0, // paid apprenticeship — no unpaid training
    yearsToHundredK: 3,
    upfrontCostUsd: 0,
    physicality: "physical",
    relocationHelps: true,
    felonyEligible: true,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["NEIEP apprenticeship (IUEC)", "Mechanic exam"],
    employers: ["Otis, Kone, Schindler, TK Elevator"],
    blurb: "One of the highest-paid trades. No school debt — you earn from day one.",
    x: 220,
    y: 320,
  },
  {
    id: "union-ironworker",
    name: "Union Ironworker (metro)",
    branch: "trades",
    tier: 3,
    medianSalary: 105000,
    hundredKPath:
      "Union locals in NYC/SF/Boston/Chicago pay $50-90/hr + OT + benefits. Regular OT gets journeymen past $100K in 2-3 yrs.",
    entryMonths: 3,
    yearsToHundredK: 2,
    upfrontCostUsd: 0,
    physicality: "physical",
    relocationHelps: true,
    felonyEligible: true,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["Local ironworkers apprenticeship (paid)"],
    employers: ["Local 40 (NYC), Local 377 (SF), Local 63 (Chicago)"],
    blurb: "Structural steel + rebar work in big-city construction. OT is the multiplier.",
    x: 130,
    y: 400,
  },
  {
    id: "pipeline-welder",
    name: "Pipeline Welder (6G)",
    branch: "trades",
    tier: 3,
    medianSalary: 110000,
    hundredKPath:
      "6G-certified welders on major oil / gas / water projects clear $100-200K with per diem. Travel is the norm.",
    entryMonths: 9,
    yearsToHundredK: 1,
    upfrontCostUsd: 8000,
    physicality: "physical",
    relocationHelps: true,
    felonyEligible: true,
    requiresHsDiploma: false,
    requires: [],
    credentials: ["Welding school 6-9mo", "AWS 6G / D1.1 certification", "CDL helpful"],
    employers: ["Pipeline contractors", "Oil & gas majors", "Public water/utility projects"],
    blurb: "The 6G rig weld is the money weld. Willingness to travel = 6-figure years.",
    x: 220,
    y: 500,
  },
  {
    id: "commercial-diver",
    name: "Underwater / Commercial Welder",
    branch: "trades",
    tier: 3,
    medianSalary: 120000,
    hundredKPath:
      "Commercial dive schools place into $100-200K work in 1-2 yrs. Saturation diving offshore pushes $250K+.",
    entryMonths: 9,
    yearsToHundredK: 2,
    upfrontCostUsd: 22000,
    physicality: "physical",
    relocationHelps: true,
    felonyEligible: true,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["ADCI commercial dive certification"],
    employers: ["Offshore energy contractors", "Bridge/dam inspection firms"],
    blurb: "Small dangerous field, big pay. The tuition is real, the ceiling is real.",
    x: 90,
    y: 280,
  },
  {
    id: "crane-operator",
    name: "Crane Operator (NCCCO)",
    branch: "trades",
    tier: 3,
    medianSalary: 100000,
    hundredKPath:
      "NCCCO tower/lattice operators in major metros bill $50-70/hr; OT pushes past $100K yr 1-2.",
    entryMonths: 6,
    yearsToHundredK: 1,
    upfrontCostUsd: 7000,
    physicality: "mixed",
    relocationHelps: true,
    felonyEligible: true,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["NCCCO certification (mobile or tower)"],
    employers: ["Crane rental cos", "GCs on high-rise / infrastructure"],
    blurb: "Short training, high responsibility, big paychecks in construction-hot cities.",
    x: 320,
    y: 250,
  },
  {
    id: "boilermaker",
    name: "Traveling Boilermaker",
    branch: "trades",
    tier: 3,
    medianSalary: 105000,
    hundredKPath:
      "Union boilermakers who travel to power / refinery / petrochem shutdowns clear $100-160K with per diem.",
    entryMonths: 0,
    yearsToHundredK: 2,
    upfrontCostUsd: 0,
    physicality: "physical",
    relocationHelps: true,
    felonyEligible: true,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["Boilermakers Local apprenticeship (paid)"],
    employers: ["Boilermakers National Joint Apprenticeship"],
    blurb: "Live out of a truck 6 months a year, come home with $100K+ banked.",
    x: 380,
    y: 380,
  },
  {
    id: "hvac-refrigeration",
    name: "Commercial Refrigeration Tech",
    branch: "trades",
    tier: 3,
    medianSalary: 100000,
    hundredKPath:
      "EPA 608 + supermarket / data-center refrigeration + on-call rotation routinely clears $100K yr 2.",
    entryMonths: 12,
    yearsToHundredK: 2,
    upfrontCostUsd: 4000,
    physicality: "physical",
    relocationHelps: false,
    felonyEligible: true,
    requiresHsDiploma: false,
    requires: [],
    credentials: ["EPA 608 Universal", "Trade-school HVAC-R program or paid apprenticeship"],
    employers: ["Mechanical contractors", "Grocery chains", "Data-center operators"],
    blurb: "Every supermarket and data center on earth needs one. On-call = the money.",
    x: 300,
    y: 470,
  },

  // =========================================================================
  // ENERGY (lower left)
  // =========================================================================
  {
    id: "nuclear-operator",
    name: "Nuclear Reactor Operator",
    branch: "energy",
    tier: 3,
    medianSalary: 115000,
    hundredKPath:
      "Utility hires you, pays you through ~18 months of training, then NRC-licenses you. $110-160K once licensed.",
    entryMonths: 18,
    yearsToHundredK: 2,
    upfrontCostUsd: 0,
    physicality: "mixed",
    relocationHelps: true,
    felonyEligible: false,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["Utility hire + in-house training", "NRC operator license"],
    employers: ["Constellation, Duke, Dominion, Southern, Vistra"],
    blurb: "Employer pays every dollar. Background check is strict — no felonies.",
    x: 200,
    y: 640,
  },
  {
    id: "power-plant-op",
    name: "Power Plant Operator",
    branch: "energy",
    tier: 3,
    medianSalary: 100000,
    hundredKPath:
      "Union scale + shift differentials + OT put non-nuclear plant ops at $100K in 2-3 yrs.",
    entryMonths: 6,
    yearsToHundredK: 2,
    upfrontCostUsd: 0,
    physicality: "mixed",
    relocationHelps: true,
    felonyEligible: true,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["Utility hire + on-the-job training"],
    employers: ["Regional utilities", "Municipal power authorities"],
    blurb: "Nights + weekends premium. Utilities pay because they train from scratch.",
    x: 130,
    y: 720,
  },
  {
    id: "oil-rig-driller",
    name: "Oil Rig Derrickhand / Driller",
    branch: "energy",
    tier: 3,
    medianSalary: 110000,
    hundredKPath:
      "Offshore roughnecks promote to derrickhand in ~1yr; drillers clear $100-160K in year 2. 14/14 rotations.",
    entryMonths: 1,
    yearsToHundredK: 2,
    upfrontCostUsd: 500,
    physicality: "physical",
    relocationHelps: true,
    felonyEligible: true,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["Rig-hand training (2 wks)", "TWIC card", "H2S / rig-pass cards"],
    employers: ["Transocean, Valaris, Noble", "Land drillers in TX, ND, NM"],
    blurb: "Two weeks on / two off. Brutal work, but you'll actually save the money.",
    x: 250,
    y: 780,
  },
  {
    id: "wind-tech-offshore",
    name: "Offshore Wind Turbine Tech",
    branch: "energy",
    tier: 3,
    medianSalary: 100000,
    hundredKPath:
      "Offshore US wind (Vineyard, Empire, Coastal Virginia) pays $100-140K with day-rates + travel — much higher than onshore.",
    entryMonths: 6,
    yearsToHundredK: 1,
    upfrontCostUsd: 4500,
    physicality: "physical",
    relocationHelps: true,
    felonyEligible: true,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["6-24mo tech program", "GWO Basic Safety Training"],
    employers: ["GE Vernova, Vestas, Siemens Gamesa", "Offshore project operators"],
    blurb: "Fastest-growing US job. Coastal states are hiring aggressively.",
    x: 350,
    y: 700,
  },

  // =========================================================================
  // TRANSPORT (bottom center-right)
  // =========================================================================
  {
    id: "atc",
    name: "Air Traffic Controller",
    branch: "transport",
    tier: 3,
    medianSalary: 137000,
    hundredKPath:
      "FAA pay scale hits $100K+ once facility-certified. Busy towers ($150K+). MUST apply before your 31st birthday.",
    entryMonths: 12,
    yearsToHundredK: 2,
    upfrontCostUsd: 0,
    physicality: "desk",
    relocationHelps: true,
    felonyEligible: false,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["AT-SA aptitude test", "FAA Academy (paid)", "Medical / clearance"],
    employers: ["FAA"],
    blurb: "Best deal in America if you're under 31. Zero out-of-pocket, six-figure ceiling.",
    x: 500,
    y: 850,
  },
  {
    id: "locomotive-engineer",
    name: "Locomotive Engineer",
    branch: "transport",
    tier: 3,
    medianSalary: 100000,
    hundredKPath:
      "Class-I railroads hire conductors, promote to engineer in 2-3 yrs. Union scale + OT = $100-150K.",
    entryMonths: 3,
    yearsToHundredK: 3,
    upfrontCostUsd: 0,
    physicality: "mixed",
    relocationHelps: true,
    felonyEligible: false,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["Railroad hire + FRA certification"],
    employers: ["Union Pacific, BNSF, CSX, Norfolk Southern, Amtrak"],
    blurb: "Railroad pays through training. Seniority = better runs + more OT.",
    x: 600,
    y: 800,
  },
  {
    id: "cdl-specialty",
    name: "Specialty CDL Driver",
    branch: "transport",
    tier: 3,
    medianSalary: 100000,
    hundredKPath:
      "Tanker / hazmat / oversize / fuel drivers with endorsements clear $100K in year 1 at the right carriers.",
    entryMonths: 2,
    yearsToHundredK: 1,
    upfrontCostUsd: 4000,
    physicality: "mixed",
    relocationHelps: true,
    felonyEligible: true,
    requiresHsDiploma: false,
    requires: [],
    credentials: ["CDL Class A", "Endorsements: H (haz), N (tank), X, T"],
    employers: ["Ashland, Kenan, Groendyke", "Big oilfield haulers"],
    blurb: "Endorsements are the multiplier. Willingness to be OTR pushes pay higher.",
    x: 720,
    y: 700,
  },
  {
    id: "owner-operator",
    name: "Owner-Operator Trucker",
    branch: "transport",
    tier: 3,
    medianSalary: 115000,
    hundredKPath:
      "Own or lease-purchase tractor + direct shipper contracts nets $100-200K after expenses. Expense discipline is everything.",
    entryMonths: 2,
    yearsToHundredK: 1,
    upfrontCostUsd: 15000,
    physicality: "mixed",
    relocationHelps: false,
    felonyEligible: true,
    requiresHsDiploma: false,
    requires: [],
    credentials: ["CDL-A", "MC / DOT authority", "Own or lease-purchase tractor"],
    employers: ["Self (direct freight, load boards)"],
    blurb: "You're running a business. If you can't manage cash flow, stay a driver.",
    x: 800,
    y: 620,
  },
  {
    id: "longshoreman",
    name: "Longshoreman (ILWU / ILA)",
    branch: "transport",
    tier: 3,
    medianSalary: 140000,
    hundredKPath:
      "West Coast ILWU registered longshoremen clear $150-200K. East/Gulf ILA similar. Getting on the casual list is competitive.",
    entryMonths: 0,
    yearsToHundredK: 2,
    upfrontCostUsd: 0,
    physicality: "physical",
    relocationHelps: true,
    felonyEligible: true,
    requiresHsDiploma: false,
    requires: [],
    credentials: ["Casual → identified casual → registered pipeline", "TWIC card"],
    employers: ["ILWU (West Coast)", "ILA (East Coast, Gulf)"],
    blurb: "No school, no cert. Hardest part is getting on the list — apply everywhere.",
    x: 830,
    y: 500,
  },

  // =========================================================================
  // PUBLIC SAFETY (top)
  // =========================================================================
  {
    id: "firefighter-metro",
    name: "Firefighter (top-pay metro)",
    branch: "public-safety",
    tier: 3,
    medianSalary: 120000,
    hundredKPath:
      "Bay Area / LA / Boston / NYC / Seattle firefighters routinely clear $150K with OT. Base alone hits $100K yr 1-3.",
    entryMonths: 6,
    yearsToHundredK: 2,
    upfrontCostUsd: 500,
    physicality: "physical",
    relocationHelps: true,
    felonyEligible: false,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["Fire academy (paid in most metros)", "EMT-B minimum, Paramedic preferred"],
    employers: ["Municipal fire departments (SF, LA, NYC, Boston, Seattle)"],
    blurb: "Pension is the sweetener. Move to a top-paying city for the base + OT.",
    x: 400,
    y: 130,
  },
  {
    id: "police-metro",
    name: "Police Officer (metro w/ OT)",
    branch: "public-safety",
    tier: 3,
    medianSalary: 110000,
    hundredKPath:
      "NYC, SF, LA, Chicago, Seattle: base + OT + specialty pay hits $100-180K by year 2-3.",
    entryMonths: 6,
    yearsToHundredK: 2,
    upfrontCostUsd: 300,
    physicality: "mixed",
    relocationHelps: true,
    felonyEligible: false,
    requiresHsDiploma: true,
    requires: [],
    credentials: ["Police academy (paid in most metros)", "State POST certification"],
    employers: ["Municipal PDs", "Sheriff's offices", "Transit / port authority PDs"],
    blurb: "OT is the multiplier. Overnight shifts, court time, details all add up.",
    x: 550,
    y: 130,
  },

  // =========================================================================
  // SALES & BUSINESS (right)
  // =========================================================================
  {
    id: "sdr",
    name: "SDR (Sales Development Rep)",
    branch: "sales-business",
    tier: 2,
    medianSalary: 70000,
    hundredKPath: "Not a $100K seat itself — the gate to becoming an AE.",
    entryMonths: 0,
    yearsToHundredK: 2,
    upfrontCostUsd: 0,
    physicality: "desk",
    relocationHelps: false,
    felonyEligible: true,
    requiresHsDiploma: false,
    requires: [],
    credentials: ["Portfolio of outbound activity", "Any hustle-visible background"],
    employers: ["B2B SaaS companies"],
    blurb: "The only entry-level desk job on this map. Grind 12-18 mo, then promote.",
    x: 830,
    y: 380,
  },
  {
    id: "saas-ae",
    name: "SaaS Account Executive",
    branch: "sales-business",
    tier: 3,
    medianSalary: 165000,
    hundredKPath:
      "OTE (on-target earnings) is $120-250K. Commission is the multiplier. Pick a category with market pull.",
    entryMonths: 0,
    yearsToHundredK: 2,
    upfrontCostUsd: 0,
    physicality: "desk",
    relocationHelps: false,
    felonyEligible: true,
    requiresHsDiploma: false,
    requires: ["sdr"],
    credentials: ["Documented quota attainment as SDR"],
    employers: ["Any B2B software company"],
    blurb: "Highest ceiling on this map with no degree. Cyclical — pick your category well.",
    x: 900,
    y: 300,
  },
  {
    id: "freight-broker",
    name: "Freight Broker Agent",
    branch: "sales-business",
    tier: 3,
    medianSalary: 100000,
    hundredKPath:
      "1099 agent with a brokerage — margin on each load. $100-250K in year 2 with a book of shippers.",
    entryMonths: 1,
    yearsToHundredK: 2,
    upfrontCostUsd: 500,
    physicality: "desk",
    relocationHelps: false,
    felonyEligible: true,
    requiresHsDiploma: false,
    requires: [],
    credentials: ["Broker training (self-study OK)", "Agent contract with a licensed brokerage"],
    employers: ["TQL, Coyote, C.H. Robinson agent programs", "Independent brokerages"],
    blurb: "Pure hustle. Phone-based. Recessions hurt; up-cycles pay stupid money.",
    x: 900,
    y: 450,
  },
  {
    id: "insurance-producer",
    name: "Commercial Insurance Producer",
    branch: "sales-business",
    tier: 3,
    medianSalary: 110000,
    hundredKPath:
      "P&C license + a book of commercial accounts pays $100-300K. First 18-24 months are lean.",
    entryMonths: 1,
    yearsToHundredK: 2,
    upfrontCostUsd: 800,
    physicality: "desk",
    relocationHelps: false,
    felonyEligible: false,
    requiresHsDiploma: false,
    requires: [],
    credentials: ["State P&C license (2 wks study)"],
    employers: ["Marsh, Aon, WTW", "Regional brokerages"],
    blurb: "Renewal commissions compound. If you build a book, income becomes annuity-like.",
    x: 810,
    y: 550,
  },

  // =========================================================================
  // TECH (upper right) — honest: fastest-realistic 2-yr window
  // =========================================================================
  {
    id: "self-taught-dev",
    name: "Self-Taught Developer (portfolio)",
    branch: "tech",
    tier: 2,
    medianSalary: 70000,
    hundredKPath:
      "Not a $100K seat itself — the gateway to cloud / security specializations that are.",
    entryMonths: 9,
    yearsToHundredK: 2,
    upfrontCostUsd: 500,
    physicality: "desk",
    relocationHelps: false,
    felonyEligible: true,
    requiresHsDiploma: false,
    requires: [],
    credentials: ["Public portfolio (GitHub)", "Optional bootcamp"],
    employers: ["Startups", "Agencies", "Remote-first cos"],
    blurb: "Hardest to break into without connections. Ship in public.",
    x: 720,
    y: 250,
  },
  {
    id: "cloud-eng",
    name: "Cloud / DevOps Engineer",
    branch: "tech",
    tier: 3,
    medianSalary: 130000,
    hundredKPath:
      "AWS / K8s certs + on-call rotation = $120-180K. Fully remote-friendly.",
    entryMonths: 0,
    yearsToHundredK: 1,
    upfrontCostUsd: 900,
    physicality: "desk",
    relocationHelps: false,
    felonyEligible: true,
    requiresHsDiploma: false,
    requires: ["self-taught-dev"],
    credentials: ["AWS Solutions Architect", "Terraform / Kubernetes exposure"],
    employers: ["SaaS cos", "Fintech", "Consultancies"],
    blurb: "Highest-paying no-degree tech role. On-call is where the total comp jumps.",
    x: 820,
    y: 180,
  },
  {
    id: "cybersec-analyst",
    name: "Cybersecurity Analyst (SOC)",
    branch: "tech",
    tier: 3,
    medianSalary: 105000,
    hundredKPath:
      "Security+ then CySA+ or Network+, land a SOC seat, hit $100K yr 2. Clearance-adjacent roles pay premium.",
    entryMonths: 6,
    yearsToHundredK: 2,
    upfrontCostUsd: 900,
    physicality: "desk",
    relocationHelps: false,
    felonyEligible: false,
    requiresHsDiploma: false,
    requires: [],
    credentials: ["CompTIA Security+", "CySA+ or Network+"],
    employers: ["MSSPs", "Enterprise SOCs", "Federal contractors"],
    blurb: "Certs matter more than a degree. Nights/weekends premium at 24/7 SOCs.",
    x: 620,
    y: 200,
  },
];
