import type { CareerNode } from "./types";

// Constellation layout: six branches radiating from a central "You" origin.
// Coordinates are in a 0-1000 x 0-1000 canvas. Origin is (500, 500).
// Each branch has Tier 1 (starter) -> Tier 2 (mid) -> Tier 3 ($100K capstone).

export const CAREERS: CareerNode[] = [
  // --- SKILLED TRADES (upper left) ---
  {
    id: "apprentice-electrician",
    name: "Apprentice Electrician",
    branch: "trades",
    tier: 1,
    medianSalary: 42000,
    hundredKPath: "Enter an IBEW or non-union apprenticeship — earn while you learn.",
    yearsToHundredK: 6,
    upfrontCostUsd: 500,
    physicality: "physical",
    relocationHelps: false,
    feltonEligible: true,
    requires: [],
    credentials: ["High school diploma / GED", "IBEW apprenticeship or state-registered program"],
    employers: ["IBEW locals", "Regional electrical contractors"],
    blurb: "Paid apprenticeship, no tuition debt. 4-5 years to journeyman.",
    x: 300,
    y: 350,
  },
  {
    id: "journeyman-electrician",
    name: "Journeyman Electrician",
    branch: "trades",
    tier: 2,
    medianSalary: 72000,
    hundredKPath: "OT + prevailing-wage projects push total comp past $100K in many metros.",
    yearsToHundredK: 5,
    upfrontCostUsd: 300,
    physicality: "physical",
    relocationHelps: true,
    feltonEligible: true,
    requires: ["apprentice-electrician"],
    credentials: ["State journeyman license"],
    employers: ["Union locals", "Industrial contractors", "Data-center builders"],
    blurb: "Licensed and mobile. Data-center and semiconductor buildouts pay top rates.",
    x: 200,
    y: 250,
  },
  {
    id: "master-electrician",
    name: "Master Electrician / Contractor",
    branch: "trades",
    tier: 3,
    medianSalary: 118000,
    hundredKPath: "Master license + business license lets you bid your own commercial jobs.",
    yearsToHundredK: 0,
    upfrontCostUsd: 5000,
    physicality: "mixed",
    relocationHelps: false,
    feltonEligible: false,
    requires: ["journeyman-electrician"],
    credentials: ["State master electrician license", "Contractor's license", "Bond & insurance"],
    employers: ["Self / small business", "Commercial construction GCs"],
    blurb: "Own your book. $100K–$250K possible; more if you employ crews.",
    x: 120,
    y: 150,
  },
  {
    id: "hvac-tech",
    name: "HVAC Technician",
    branch: "trades",
    tier: 1,
    medianSalary: 52000,
    hundredKPath: "Add EPA + refrigeration + on-call commercial work.",
    yearsToHundredK: 5,
    upfrontCostUsd: 3500,
    physicality: "physical",
    relocationHelps: true,
    feltonEligible: true,
    requires: [],
    credentials: ["EPA 608 certification", "6-24mo trade school or apprenticeship"],
    employers: ["Mechanical contractors", "Facilities teams"],
    blurb: "Enter fast. Commercial refrigeration and controls specialists clear $100K.",
    x: 380,
    y: 280,
  },
  {
    id: "elevator-mechanic",
    name: "Elevator Mechanic",
    branch: "trades",
    tier: 3,
    medianSalary: 102000,
    hundredKPath: "NEIEP apprenticeship then union scale — one of the highest-paid trades from day one.",
    yearsToHundredK: 4,
    upfrontCostUsd: 0,
    physicality: "physical",
    relocationHelps: true,
    feltonEligible: true,
    requires: [],
    credentials: ["NEIEP apprenticeship (IUEC)", "Mechanic exam"],
    employers: ["Otis, Kone, Schindler, TK Elevator"],
    blurb: "Small field, high pay. Waitlists in most cities; move for a slot.",
    x: 230,
    y: 420,
  },

  // --- HEALTHCARE (upper right) ---
  {
    id: "cna",
    name: "CNA / Medical Assistant",
    branch: "healthcare",
    tier: 1,
    medianSalary: 36000,
    hundredKPath: "Foot in the door. Employers often pay for the next credential.",
    yearsToHundredK: 6,
    upfrontCostUsd: 1200,
    physicality: "physical",
    relocationHelps: false,
    feltonEligible: false,
    requires: [],
    credentials: ["State CNA certificate (4-12 weeks)"],
    employers: ["Hospitals", "Skilled nursing facilities"],
    blurb: "Cheapest, fastest entry into healthcare. Pipeline to sonography/radiology.",
    x: 620,
    y: 280,
  },
  {
    id: "sonographer",
    name: "Diagnostic Medical Sonographer",
    branch: "healthcare",
    tier: 3,
    medianSalary: 84000,
    hundredKPath: "Cardiac or vascular specialty + night/travel shifts crosses $100K.",
    yearsToHundredK: 2,
    upfrontCostUsd: 15000,
    physicality: "mixed",
    relocationHelps: true,
    feltonEligible: false,
    requires: ["cna"],
    credentials: ["ARDMS certification", "Accredited 18-24mo sonography program"],
    employers: ["Hospitals", "Imaging centers", "Travel agencies"],
    blurb: "No 4-yr degree needed. Cardiac sonographers routinely clear $110K.",
    x: 720,
    y: 200,
  },
  {
    id: "radiation-therapist",
    name: "Radiation Therapist",
    branch: "healthcare",
    tier: 3,
    medianSalary: 98000,
    hundredKPath: "Associate's-level; senior/lead roles and metro hospitals push past six figures.",
    yearsToHundredK: 3,
    upfrontCostUsd: 18000,
    physicality: "mixed",
    relocationHelps: true,
    feltonEligible: false,
    requires: ["cna"],
    credentials: ["ARRT (T) credential", "Accredited associate program"],
    employers: ["Cancer centers", "Academic hospitals"],
    blurb: "Small field, strong ceiling, no bachelor's required in most states.",
    x: 780,
    y: 320,
  },

  // --- TECH (right) ---
  {
    id: "self-taught-dev",
    name: "Self-Taught Developer",
    branch: "tech",
    tier: 1,
    medianSalary: 55000,
    hundredKPath: "Ship a portfolio, land junior remote role, level to mid in 2-3 yrs.",
    yearsToHundredK: 4,
    upfrontCostUsd: 500,
    physicality: "desk",
    relocationHelps: false,
    feltonEligible: true,
    requires: [],
    credentials: ["Public portfolio (GitHub)", "Bootcamp optional"],
    employers: ["Startups", "Agencies", "Remote-first cos"],
    blurb: "Hardest to start, biggest ceiling. Remote-friendly.",
    x: 820,
    y: 500,
  },
  {
    id: "cloud-eng",
    name: "Cloud / DevOps Engineer",
    branch: "tech",
    tier: 3,
    medianSalary: 128000,
    hundredKPath: "AWS/GCP certs + on-call rotation = $120-180K without a degree.",
    yearsToHundredK: 2,
    upfrontCostUsd: 800,
    physicality: "desk",
    relocationHelps: false,
    feltonEligible: true,
    requires: ["self-taught-dev"],
    credentials: ["AWS Solutions Architect", "Terraform / Kubernetes exposure"],
    employers: ["SaaS companies", "Fintech", "Consultancies"],
    blurb: "Highest-paying tech role you can enter without a CS degree.",
    x: 900,
    y: 420,
  },
  {
    id: "cybersec-analyst",
    name: "Cybersecurity Analyst",
    branch: "tech",
    tier: 3,
    medianSalary: 112000,
    hundredKPath: "Security+ then CySA+ or OSCP; SOC roles routinely clear $100K in 3 yrs.",
    yearsToHundredK: 3,
    upfrontCostUsd: 900,
    physicality: "desk",
    relocationHelps: false,
    feltonEligible: false,
    requires: [],
    credentials: ["CompTIA Security+", "CySA+ or OSCP"],
    employers: ["MSSPs", "Enterprise SOCs", "Federal contractors"],
    blurb: "Certs matter more than degree. Clearance-adjacent roles pay premium.",
    x: 900,
    y: 580,
  },

  // --- TRANSPORT & ENERGY (lower right) ---
  {
    id: "cdl-a",
    name: "CDL-A Driver",
    branch: "transport-energy",
    tier: 1,
    medianSalary: 62000,
    hundredKPath: "Owner-operator or specialized (tanker/oversize) doubles pay.",
    yearsToHundredK: 3,
    upfrontCostUsd: 4000,
    physicality: "mixed",
    relocationHelps: true,
    feltonEligible: true,
    requires: [],
    credentials: ["CDL Class A", "Endorsements (H, T, N)"],
    employers: ["Regional carriers", "Owner-operator"],
    blurb: "3-8 weeks to license. Ownership + specialty freight is the $100K path.",
    x: 720,
    y: 700,
  },
  {
    id: "owner-operator",
    name: "Owner-Operator Trucker",
    branch: "transport-energy",
    tier: 3,
    medianSalary: 115000,
    hundredKPath: "Own tractor + direct shipper contracts. Nets $100-200K after expenses.",
    yearsToHundredK: 0,
    upfrontCostUsd: 25000,
    physicality: "mixed",
    relocationHelps: false,
    feltonEligible: true,
    requires: ["cdl-a"],
    credentials: ["MC / DOT authority", "Own or lease-purchase tractor"],
    employers: ["Self (direct freight, load boards)"],
    blurb: "The trades version of running your own business. Watch expense discipline.",
    x: 780,
    y: 800,
  },
  {
    id: "wind-tech",
    name: "Wind Turbine Technician",
    branch: "transport-energy",
    tier: 2,
    medianSalary: 61000,
    hundredKPath: "Senior/lead + offshore or high-plains projects push past $100K.",
    yearsToHundredK: 5,
    upfrontCostUsd: 4500,
    physicality: "physical",
    relocationHelps: true,
    feltonEligible: true,
    requires: [],
    credentials: ["6-24mo technical program", "GWO Basic Safety Training"],
    employers: ["GE Vernova, Vestas, Siemens Gamesa"],
    blurb: "Fastest-growing US job. Must be OK with heights and remote work sites.",
    x: 660,
    y: 780,
  },
  {
    id: "power-plant-op",
    name: "Power Plant Operator",
    branch: "transport-energy",
    tier: 3,
    medianSalary: 100000,
    hundredKPath: "Union scale + shift differentials. Nuclear ops higher still.",
    yearsToHundredK: 4,
    upfrontCostUsd: 0,
    physicality: "mixed",
    relocationHelps: true,
    feltonEligible: false,
    requires: [],
    credentials: ["Utility hire + 2-4 yrs on-the-job", "NRC license (nuclear)"],
    employers: ["Regional utilities", "Nuclear operators"],
    blurb: "Employer trains you. Nuclear-licensed operators can reach $140K+.",
    x: 830,
    y: 720,
  },

  // --- SALES / BUSINESS (lower left) ---
  {
    id: "sdr",
    name: "SDR (Sales Development Rep)",
    branch: "sales-business",
    tier: 1,
    medianSalary: 68000,
    hundredKPath: "Promote to AE in 12-18mo; SaaS AE OTE is $120-200K.",
    yearsToHundredK: 3,
    upfrontCostUsd: 0,
    physicality: "desk",
    relocationHelps: false,
    feltonEligible: true,
    requires: [],
    credentials: ["No formal cert; hiring is portfolio-of-outreach based"],
    employers: ["B2B SaaS companies"],
    blurb: "The only entry-level office job on this map. Grind for 18 months.",
    x: 280,
    y: 650,
  },
  {
    id: "saas-ae",
    name: "SaaS Account Executive",
    branch: "sales-business",
    tier: 3,
    medianSalary: 155000,
    hundredKPath: "OTE (on-target-earnings) $120-250K; commission is the multiplier.",
    yearsToHundredK: 0,
    upfrontCostUsd: 0,
    physicality: "desk",
    relocationHelps: false,
    feltonEligible: true,
    requires: ["sdr"],
    credentials: ["Track record of quota attainment"],
    employers: ["Any B2B software company"],
    blurb: "Highest ceiling on this map. Cyclical — pick a category that will grow.",
    x: 180,
    y: 750,
  },
  {
    id: "real-estate-agent",
    name: "Real Estate Agent",
    branch: "sales-business",
    tier: 2,
    medianSalary: 52000,
    hundredKPath: "Top-quartile agents in decent metros clear $100K in year 3+.",
    yearsToHundredK: 3,
    upfrontCostUsd: 2500,
    physicality: "mixed",
    relocationHelps: false,
    feltonEligible: false,
    requires: [],
    credentials: ["State real estate license (3-6 months)"],
    employers: ["Brokerages (Compass, KW, eXp, indie)"],
    blurb: "Cheap license, brutal first 2 years. Warm-market network is everything.",
    x: 380,
    y: 720,
  },
  {
    id: "insurance-broker",
    name: "Commercial Insurance Broker",
    branch: "sales-business",
    tier: 3,
    medianSalary: 108000,
    hundredKPath: "Book of business + renewals compound. Producers hit $100-300K.",
    yearsToHundredK: 4,
    upfrontCostUsd: 1000,
    physicality: "desk",
    relocationHelps: false,
    feltonEligible: false,
    requires: [],
    credentials: ["State P&C license", "CIC / CPCU designations optional"],
    employers: ["Marsh, Aon, WTW, mid-market brokerages"],
    blurb: "Overlooked. Recurring commissions make year 5+ salaries fat.",
    x: 320,
    y: 830,
  },

  // --- PUBLIC SAFETY (top center) ---
  {
    id: "firefighter",
    name: "Firefighter",
    branch: "public-safety",
    tier: 2,
    medianSalary: 54000,
    hundredKPath: "OT-heavy metros (Bay Area, LA, NYC, Boston) push line firefighters past $100K.",
    yearsToHundredK: 5,
    upfrontCostUsd: 500,
    physicality: "physical",
    relocationHelps: true,
    feltonEligible: false,
    requires: [],
    credentials: ["Fire academy", "EMT-B minimum"],
    employers: ["Municipal fire departments"],
    blurb: "Great pensions. Total comp with OT crosses $150K in top-paying cities.",
    x: 480,
    y: 180,
  },
  {
    id: "air-traffic-controller",
    name: "Air Traffic Controller",
    branch: "public-safety",
    tier: 3,
    medianSalary: 137000,
    hundredKPath: "Federal pay scale; even entry-tower work at busy facilities crosses $100K.",
    yearsToHundredK: 3,
    upfrontCostUsd: 0,
    physicality: "desk",
    relocationHelps: true,
    feltonEligible: false,
    requires: [],
    credentials: ["FAA Academy (must apply before age 31)", "AT-SA aptitude test"],
    employers: ["FAA"],
    blurb: "Age limit is real. If you're under 31, this is one of the best deals in America.",
    x: 560,
    y: 120,
  },
];
